<?php

/**
 * @file
 * Contains module file.
 */

declare(strict_types=1);

use Drupal\ui_styles_ckeditor5\HookHandler\LibraryInfoAlter;

/**
 * Implements hook_library_info_alter().
 */
function ui_styles_ckeditor5_library_info_alter(array &$libraries, string $extension): void {
  /** @var \Drupal\ui_styles_ckeditor5\HookHandler\LibraryInfoAlter $instance */
  $instance = \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(LibraryInfoAlter::class);
  $instance->alter($libraries, $extension);
}
