<?php

/**
 * @file
 * Adding styles to regions.
 */

declare(strict_types=1);

use Drupal\ui_styles_page\HookHandler\PreprocessRegion;
use Drupal\ui_styles_page\UiStylesPageInterface;

/**
 * Implements hook_preprocess_region().
 */
function ui_styles_page_preprocess_region(array &$variables): void {
  /** @var \Drupal\ui_styles_page\HookHandler\PreprocessRegion $instance */
  $instance = \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(PreprocessRegion::class);
  $instance->preprocess($variables);
}

/**
 * Implements hook_config_schema_info_alter().
 */
function ui_styles_page_config_schema_info_alter(array &$definitions): void {
  if (!isset($definitions['theme_settings']['mapping'])) {
    return;
  }

  $definitions['theme_settings']['mapping'][UiStylesPageInterface::REGION_STYLES_KEY_THEME_SETTINGS] = [
    'type' => 'ui_styles_regions',
  ];
}
